# Changes here will be overwritten by Copier
Authors: Michael Boyle <michael.oliver.boyle@gmail.com>
JuliaMinVersion: '1.10'
License: MIT
LicenseCopyrightHolders: Michael Boyle
PackageName: PostNewtonian
PackageOwner: moble
PackageUUID: 377afc40-5642-4616-8613-b7ebca523866
StrategyConfirmIncluded: false
StrategyLevel: 2
StrategyReviewExcluded: false
_commit: v0.16.2
_src_path: https://github.com/JuliaBesties/BestieTemplate.jl
