# Changes here will be overwritten by Copier
AddAllcontributors: false
AddCodeOfConduct: false
AddContributionDocs: true
AddCopierCI: true
AddGitHubTemplates: true
AddMacToCI: true
AddPrecommit: true
AddWinToCI: true
AnswerStrategy: ask
AuthorEmail: michael.oliver.boyle@gmail.com
AuthorName: Michael Boyle
Indentation: 4
JuliaMinVersion: '1.6'
License: MIT
PackageName: PostNewtonian
PackageOwner: moble
PackageUUID: 377afc40-5642-4616-8613-b7ebca523866
RunJuliaNightlyOnCI: false
UseCirrusCI: false
_commit: v0.9.1
_src_path: https://github.com/abelsiqueira/BestieTemplate.jl
