# Use Blue style by default, but set some customizations
for_in_replacement = "∈"
ignore = ["src/pn_expressions/mode_weights.jl"]
import_to_using = false
normalize_line_endings = "unix"
style = "blue"
