name = "ZeroEccParamsFromPN"
uuid = "8a1bce5d-dbb4-42a5-bfda-c87e1ca6047e"
authors = ["Mike Boyle <michael.oliver.boyle@gmail.com>"]
version = "0.1.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
PostNewtonian = "377afc40-5642-4616-8613-b7ebca523866"
Quaternionic = "0756cd96-85bf-4b6f-a009-b5012ea7a443"

[compat]
ArgParse = "1.2.0"
PostNewtonian = "0.10.6"
Quaternionic = "3.0.0"
